#' @function predReco: script to predict ecosystem R using pretrained NN models
#' with bias correction for Tsoil (due to soil layer mismatches)
#' this subroutine stores Reco as tif files for each time stamp
#' @author: Dien Wu, 05/28/2019 

# ---------------------------------------------------------------------------- #
#' @param site site name, e.g., 'SaltLakeCity', without any space
#' @param minlon maxlon, minlat, maxlat: spatial domain for Reco calculations
#' @param gf.dlon gf.dlat: spatial domain for urban gap filling, 
#'                e.g., dlon = dlat = 1 for 2x2 deg around @site

#' @param timestr YYYYMMDD
#' @param gpp.file path + filename of calculated GPP rasterStack, see main_script_GPP.r
#' @param lc.file path + filename for MCD Land cover for the desired region 
#'                file should be in tif format, annual file downloaded from
#'                https://lpdaacsvc.cr.usgs.gov/appeears/, 


#' @param TA.path path for daymet 
#' @param TA.field which Tair fields to use, either 'daymet' or 'ERA5'
#' @param TA.varname the common characters in the names of all files in @param TA.path, 
#'                 e.g., TA.varname = 'daymet_v3', for 'daymet_v3_t*_*_na.nc4'
#'                   OR  TA.varname = '2T' for '2T_*.nc'

#' @param TS.path path for NLDAS or ERA5 for US or global Reco
#' @param TS.field which temperature fields to use, either 'NLDAS' or 'ERA5'
#' @param TS.varname the common characters in the names of all files in @param TS.path, 
#'        e.g., TS.varname = 'TSOIL', in 'NLDAS_NOAH0125_H.AYYYYMMDD.HHSS*.nc4'
#'          OR  TS.varname = 'STL1' for 'STL1_YYYYMM.nc'

#' @param nn.dir path for pretrained NN models, see NN_train_reco.r + prep_NN_train_reco.r
#' @param nn.pattern common characters in NN rds filenames
#' @param reco.path path for storing Reco for natural biomes and figures
#' @param smurf_wd path for this bio model repositor

#' @param skip.igbp NO NN models for those IGBP types, will skip those types 
#'                for Reco estimates, default are DBF, EBF, CRO/NVM for US 
#' @param tmpdir temporary space for large raster calculations 

# ---------------------------------------------------------------------------- #
#' updates: 
#' 06/14/2019 move parts of scripts from the main script to this subroutine, DW
#' 06/17/2019 use biomes-weighted mean Reco for urban Reco, DW
#' 06/18/2019 incorporate parallel computation to speed up the calculation, DW
#' 07/01/2019 add Tsoil bias corrections due to mismtaches in soil layers 
#'            between FLUXNET and modeled fields, DW
#' 08/01/2019 remove Tsoil bias correction, use modeled Tsoil for NN training, DW
#' 08/02/2019 add Reco uncertainty from RMSE and CV of the NN-predict vs. obs Reco
#'            this set of uncertainty depends on IGBP
#' 09/10/2019, use updated Land Cover tif generated from main_script_GPP.r
#' 12/02/2019, for a few grid cells near water bodies whose temps are NA, 
#'             use a simple linear relation between GPP and Reco, ~ about half
#' 03/02/2020, DW, reuse the vegetated fractions generated by 'main_script_GPP.r'

# ---------------------------------------------------------------------------- #
### predReco
predReco_biome <- function(reg.name = 'westernCONUS', 
                           reg.path, 
                           minlon = -125, # in deg, negative for west hemisphere
                           maxlon = -95,  # in deg
                           minlat = 30, 
                           maxlat = 50,
                           timestr = '20150618',      # in YYYYMMDD, UTC time
                           lc.path,   
                           lc.pattern, 

                           TA.path, 
                           TA.field = c('daymet', 'ERA5')[1], 
                           TA.varname = c('daymet_v3', '2T')[1], 
                           TS.path, 
                           TS.field = c('NLDAS', 'ERA5')[1], 
                           TS.varname = c('TSOIL', 'STL1')[1], 
                           nn.pattern = c('daymet_nldas', 'era5')[1],  
                           nn.platform = c('keras', 'neuralnet')[1], 

                           smurf_wd = getwd(),  # working directory 
                           tmpdir = NA) {
  
  try({

    # Ensure dependencies are loaded for current node/process
    setwd(smurf_wd); source(file.path(smurf_wd, 'r/dependencies.r'), local = T)
    if (nn.platform == 'keras') 
      source(file.path(smurf_wd, 'r/keras.dependencies.r'), local = T)

    if (!is.na(tmpdir)) raster::rasterOptions(tmpdir = tmpdir)
    timestr <- paste0(timestr, '00')    # YYYYMMDD 00 UTC

    cat(paste('\n\n# ------- Working on time', timestr, 'for', reg.name, '------#\n'))
    yr <- as.numeric(substr(timestr, 1, 4))
    reg.ext <- raster::extent(minlon, maxlon, minlat, maxlat) # regional extent

    # outpath for Reco
    reco.path <- file.path(reg.path, paste0('daily_mean_Reco_', nn.platform), nn.pattern, yr)
    dir.create(reco.path, showWarnings = F, recursive = T)
    

    # ---------------------- Step 1. PREPARE ALL INPUT ----------------------- #
    cat(paste('\n\n# --------- Step 1: Preparing data for', timestr, '-------- #\n'))
    # call prep.input4reco() to get all input variables and form them into 
    # the correct grid spacing, will return a RasterBrick
    gpp.files <- list.files(reg.path, 'daily_mean_SIF_GPP_uncert', full.names = T)
    gpp.file  <- gpp.files[grepl(yr, gpp.files)]  # one GPP file per year
    if (length(gpp.file) == 0) stop('NO GPP files found...see `main_script_GPP.r`\n')

    prep.list <- prep.input4reco(reg.ext, reg.path, reg.name, timestr, 
                                 TA.field, TA.path, TA.varname, 
                                 TS.field, TS.path, TS.varname, 
                                 lc.path, lc.pattern, gpp.file) 
    mean.gpp.rt <- prep.list$init.gpp.stk$GPP_mean  # best-estimated GPP at 0.05deg
    

    # -------------------- Step 2. PREDICT Reco per IGBP -------------------- #
    # call predReco.loopv2() to predict Reco, will return two rasters
    cat('predReco(): # --------- Step 2: Predicting Reco --------- #\n')
    #' @param prep.list should be a list containing a rasterBrick of TA, TS, and GPP, 
    #' a rasterLayer of Land cover type, and a rasterStack of vegetated fractions
    #' prep.list can be prepared by calling prep.input4reco()
    nn.dir <- file.path(smurf_wd, 'data/NN_models', nn.platform)

    if (nn.platform == 'neuralnet') 
        pred.stk <- predReco_loop_neuralnet(prep.list, nn.dir, nn.pattern)

    if (nn.platform == 'keras') {
        nn.file <- file.path(nn.dir, 'nn_era5_mon_season_igbp.h5')
        pred.stk <- predReco_loop_kerasv2(timestr, prep.list, nn.file)
    }
    
    mean.reco.rt <- pred.stk$reco.mean      # as rasterLayer
    sd.reco.rt   <- pred.stk$reco.sd
    
    # degbug on NA reco (reasons: no Tsoil, skip igbp, no nn models)
    #na.df <- pred.df %>% filter(is.na(Reco), !name %in% skip.igbp, !is.na(Tsoil))


    # ------------ Step 3. AGGREGATE fluxes from 500m to 0.05deg ------------- #
    cat('predReco(): # ------- Step 3: Aggregating 500m Reco to 0.05deg -------- #\n')

    # factor in each lon/lat direction, total N is fact^2
    # aggregating best-estimated Reco from 500m to 0.05deg
    # do not use projectRaster, DW, 08/13/2019
    # use aggregate, its default operation is taking the mean of all 500m reco
    fact <- res(mean.gpp.rt)[1] / res(mean.reco.rt)[1]  
    mean.reco.agg <- raster::aggregate(mean.reco.rt, fact = fact) 

    # calculate the sum of error variances 
    sd.reco.agg <- sqrt(raster::aggregate(sd.reco.rt^2, fact = fact, FUN = mean))  

    # if reco_sd grid does not match gpp grid, then reproject after above aggregation
    if (compareRaster(mean.reco.agg, mean.gpp.rt) * 
        compareRaster(sd.reco.agg,   mean.gpp.rt) == 0) {
        mean.reco.agg <- raster::projectRaster(mean.reco.agg, mean.gpp.rt)  
        sd.reco.agg <- raster::projectRaster(sd.reco.agg, mean.gpp.rt)  
    }   # end if


    # ---------------------- force negative Reco as zero --------------------- #
    # negative Reco occurs due to potential NN extrapolation, DW, 06/18/2019 
    # where modeled gridded temperatures < observed temperatures
    mean.reco.agg[mean.reco.agg < 0] <- 0   
    sd.reco.agg[sd.reco.agg < 0] <- 0   

    # ***** names of each rasterLayer or stack should indicate the time, 
    #       with correct form in POSIXct() initially *****
    names(mean.reco.agg) <- as.POSIXct(timestr, format = '%Y%m%d%H', tz = 'UTC')
    names(sd.reco.agg) <- as.POSIXct(timestr, format = '%Y%m%d%H', tz = 'UTC')

    # as a sanity check, plot GPP and Reco 
    #levelplot(stack(mean.gpp.rt, mean.reco.agg))


    # -------------------- Step 4. STORE 0.05deg RECO ----------------------- #
    cat(paste('\n\nStep 4: Storing 0.05 deg daily mean Reco in .nc for', timestr, '\n'))
    varnames  <- c('Reco_mean', 'Reco_sd')
    varunits  <- rep('umol m-2 s-1', length(varnames))
    longnames <- c('Daily Mean Ecosystem Respiration (best estimates)', 
                   '1-sigma Uncertainty of Daily Mean Ecosystem Respiration')
    zformat <- 'X%Y.%m.%d'

    stk.list <- list(mean.reco.agg, sd.reco.agg); names(stk.list) <- varnames
    reco.fn <- file.path(reco.path, paste0('daily_mean_Reco_uncert_', reg.name, '_', 
                                           substr(timestr, 1, 8), '.nc'))

    save.raster2nc(varnames, varunits, longnames, zformat, stk.list, 
                   filename = reco.fn)
    gc() 
    return(reco.fn)
  })  # end of try()
}   

# end of subroutine
