#' @function predReco: script to predict ecosystem R using pretrained NN models
#' with bias correction for TS (due to soil layer mismatches)
#' this subroutine stores Reco as tif files for each time stamp
#' @author: Dien Wu, 05/28/2019 

# ---------------------------------------------------------------------------- #
#' @param site site name, e.g., 'SaltLakeCity', without any space
#' @param minlon maxlon, minlat, maxlat: spatial domain for Reco calculations
#' @param gf.dlon gf.dlat: spatial domain for urban gap filling, 
#'                e.g., dlon = dlat = 1 for 2x2 deg around @site

#' @param timestr YYYYMMDD
#' @param gpp.file path + filename of calculated GPP rasterStack, see main_script_GPP.r
#' @param lc.file path + filename for MCD Land cover for the desired region 
#'                file should be in tif format, annual file downloaded from
#'                https://lpdaacsvc.cr.usgs.gov/appeears/, 


#' @param TA.path path for daymet 
#' @param TA.field which TA fields to use, either 'daymet' or 'ERA5'
#' @param TA.varname the common characters in the names of all files in @param TA.path, 
#'                 e.g., TA.varname = 'daymet_v3', for 'daymet_v3_t*_*_na.nc4'
#'                   OR  TA.varname = '2T' for '2T_*.nc'

#' @param TS.path path for NLDAS or ERA5 for US or global Reco
#' @param TS.field which temperature fields to use, either 'NLDAS' or 'ERA5'
#' @param TS.varname the common characters in the names of all files in @param TS.path, 
#'        e.g., TS.varname = 'TS', in 'NLDAS_NOAH0125_H.AYYYYMMDD.HHSS*.nc4'
#'          OR  TS.varname = 'STL1' for 'STL1_YYYYMM.nc'

#' @param nn.dir path for pretrained NN models, see NN_train_reco.r + prep_NN_train_reco.r
#' @param nn.pattern common characters in NN rds filenames
#' @param reco.path path for storing Reco for natural biomes and figures
#' @param smurf_wd path for this bio model repositor

#' @param skip.igbp NO NN models for those IGBP types, will skip those types 
#'                for Reco estimates, default are DBF, EBF, CRO/NVM for US 
#' @param tmpdir temporary space for large raster calculations 

# ---------------------------------------------------------------------------- #
#' updates: 
#' 06/14/2019 move parts of scripts from the main script to this subroutine, DW
#' 06/17/2019 use biomes-weighted mean Reco for urban Reco, DW
#' 06/18/2019 incorporate parallel computation to speed up the calculation, DW
#' 07/01/2019 add TS bias corrections due to mismtaches in soil layers 
#'            between FLUXNET and modeled fields, DW
#' 08/01/2019 remove TS bias correction, use modeled TS for NN training, DW
#' 08/02/2019 add Reco uncertainty from RMSE and CV of the NN-predict vs. obs Reco
#'            this set of uncertainty depends on IGBP
#' 09/10/2019, use updated Land Cover tif generated from main_script_GPP.r
#' 12/02/2019, for a few grid cells near water bodies whose temps are NA, 
#'             use a simple linear relation between GPP and Reco, ~ about half
#' 03/02/2020, DW, reuse the vegetated fractions generated by 'main_script_GPP.r'

# ---------------------------------------------------------------------------- #
### predReco
predReco_keras <- function(reg.name = 'westernCONUS', 
                            reg.path, 
                            minlon = -125, # in deg, negative for west hemisphere
                            maxlon = -95,  # in deg
                            minlat = 30, 
                            maxlat = 50,
                            timestr = '20150618',      # in YYYYMMDD, UTC time

                            lc.path, 
                            lc.pattern, 
                            gpp.file, 
                            TA.path, 
                            TA.field = c('daymet', 'ERA5')[1], 
                            TA.varname = c('daymet_v3', '2T')[1], 
                            TS.path, 
                            TS.field = c('NLDAS', 'ERA5')[1], 
                            TS.varname = c('TS', 'STL1')[1], 
                            smurf_wd = getwd(),  # working directory 
                            tmpdir = NULL) {
  
  try({

    # Ensure dependencies are loaded for current node/process
    setwd(smurf_wd); source(file.path(smurf_wd, 'r/keras.dependencies.r'), local = T)
    if (!is.null(tmpdir)) raster::rasterOptions(tmpdir = tmpdir)
    
    timestr <- paste0(timestr, '00')    # YYYYMMDD 00 UTC

    cat(paste('\n\n# ------- Working on time', timestr, 'for', reg.name, '------#\n'))
    yr <- as.numeric(substr(timestr, 1, 4))

    # outpath for Reco
    #reco.path <- file.path(reg.path, 'daily_mean_Reco_keras', yr)
    reco.dir <- paste0('daily_mean_Reco_', tolower(TA.field), '_', tolower(TS.field))
    reco.path <- file.path(reg.path, reco.dir, yr)
    dir.create(reco.path, showWarnings = F, recursive = T)


    # ---------------------- Step 1. PREPARE ALL INPUT ----------------------- #
    cat(paste('\n\n# --------- Step 1: Preparing GPP+TA+TS for', timestr, '-------- #\n'))
    reg.ext <- raster::extent(minlon, maxlon, minlat, maxlat)

    # call prep.input4reco() to get all input variables and form them into 
    # the correct grid spacing, will return a RasterBrick
    input.brk <- prep.input4reco.keras(reg.ext, reg.path, reg.name, timestr, 
                                       TA.field, TA.path, TA.varname, 
                                       TS.field, TS.path, TS.varname, gpp.file) 

    # also load land cover data 
    lc.rt <- prep.mcd12(lc.path, lc.pattern, yr, lc.max.yr = 2018, reg.name, reg.ext)


    # -------------------- Step 2. PREDICT Reco per IGBP -------------------- #
    # call predReco.loopv2() to predict Reco, will return two rasters
    cat('\n\n# --------- Step 2: Predicting Reco --------- #\n')
    pred.stk <- predReco_loop_keras(input.brk, TA.field, TS.field, lc.rt, smurf_wd) 
    
    # Reco already in 0.05deg with unit of umol m-2 s-1, 
    # since NN model is trained based on (umol m-2 s-1) : (umol m-2 s-1)
    mean.reco <- pred.stk$Reco; mean.reco[mean.reco < 0] <- 0
    sd.reco   <- pred.stk$Reco_sd; sd.reco[sd.reco < 0] <- 0

    # ***** names of each rasterLayer or stack should indicate the time, 
    #       with correct form in POSIXct() initially *****
    names(mean.reco) <- as.POSIXct(timestr, format = '%Y%m%d%H', tz = 'UTC')
    names(sd.reco) <- as.POSIXct(timestr, format = '%Y%m%d%H', tz = 'UTC')


    # -------------------- Step 3. STORE 0.05deg RECO ----------------------- #
    cat(paste('\n\n# --------- Step 3: Storing 0.05 deg daily mean Reco in .nc for', 
        timestr, ' -------- #\n'))
        
    varnames  <- c('Reco_mean', 'Reco_sd')
    varunits  <- rep('umol m-2 s-1', length(varnames))
    longnames <- c('Daily Mean Ecosystem Respiration (best estimates)', 
                   '1-sigma Uncertainty of Daily Mean Ecosystem Respiration')
    zformat <- 'X%Y.%m.%d'

    stk.list <- list(mean.reco, sd.reco); names(stk.list) <- varnames

    reco.fn <- file.path(reco.path, paste0('daily_mean_Reco_uncert_', reg.name, 
                                           '_', substr(timestr, 1, 8), '.nc'))

    save.raster2nc(varnames, varunits, longnames, zformat, stk.list, 
                   filename = reco.fn)
    
    return(reco.fn)
  })  # end of try()
}   

# end of subroutine
